# Generated by Django 4.0.6 on 2022-07-20 17:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subcription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('pairPoint', models.IntegerField()),
                ('playerOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.registration')),
            ],
        ),
    ]
