# Generated by Django 4.0.6 on 2022-07-20 17:56

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, primary_key=True, serialize=False, verbose_name='cpf'),
        ),
    ]
