# Generated by Django 4.0.6 on 2022-07-20 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_registration_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcription',
            name='playerTwo',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='playerTwo', to='games.registration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='points',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='subcription',
            name='pairPoint',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='subcription',
            name='playerOne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerOne', to='games.registration'),
        ),
    ]
