# Generated by Django 4.0.6 on 2022-07-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_subcription_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(default='null', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.CharField(default=123456, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcription',
            name='category',
            field=models.CharField(choices=[('FIni', 'Feminino Iniciante'), ('FInt', 'Feminino Intermediário'), ('FAva', 'Feminino Avançado'), ('MIni', 'Masculino Iniciante'), ('MInt', 'Masculino Intermediário'), ('MAva', 'Masculino Avançado')], max_length=4),
        ),
    ]
