# Generated by Django 4.0.6 on 2022-07-21 14:25

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_registration_email_registration_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
